version: 2

# References to reduce duplication in the rest of the config
references:
  container: &container_config
    docker:
      - image: circleci/ruby:2.3-node
  cache_dependencies: &cache_dependencies
    save_cache:
      key: dependency-cache-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - dependency-cache-{{ checksum "Gemfile.lock" }}
        - dependency-cache-

# Circle jobs
jobs:

  # Verify code then run unit and integration tests
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_dependencies
      - run:
          name: Install dependencies
          command: make install
      - *cache_dependencies
      - run:
          name: Serve the website
          command: make serve
          background: true
      - run:
          name: Wait for website to start
          command: sleep 5
      - run:
          name: Run accessibility tests
          command: make test

# Circle workflows
workflows:
  version: 2
  test:
    jobs:
      - test
